language: node_js
before_deploy: |
  PKG_VERSION=$(node -p "require('./package.json').version")
  SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
  NPM_TAG="latest"

  if [[ "${PKG_VERSION}" = *-pre ]]; then
    NPM_TAG="next"
  fi
  echo "NPM_TAG=${NPM_TAG}"

  # If this is a pre-release version, give the package a unique version so we can publish it to npm
  # (as npm does not allow us to overwrite previously published packages)
  if [ "$NPM_TAG" == "next" ]; then
    UNIQUE_PKG_VERSION="${PKG_VERSION}.${SHORT_COMMIT_HASH}"
    npm version ${UNIQUE_PKG_VERSION}
    echo "Set package version to ${UNIQUE_PKG_VERSION}"
    cat package.json
  fi
deploy:
  skip_cleanup: true
  provider: npm
  email:
    secure: GjgqKh0vwSx0couRZ0V5Ic0WiT0isgJ3zF6D/gCSpHn++NR59SdicS+T3NdsJNE8p8DJYNsA93C4YmGQ5G3XG/oOT2LfrtjzQXcdrtGPws1E7ZWsbTZO9zBje/+umO+G1eFa4m+ShMtJf0rqGfsI/h42LXfvwEDTnwpZW62JG2/I2JzsxWYSd6Vb5I1/Wry2D9eylshxbrTPlZlDBKCqMgqcglTTD69NkDveMaGtsbwxL8UX/ISN8rlz+ZMd6BWrmm6MaZQpS5XplL4pcCcxhVh6VepxpjEHvEbeEVlYO3SuUcKgD1TwU5JLG9S+OhKQ1Avc/7fHcIpUt55yEAOwD2Sri5O8I7I6eZMA02RH5EVt4FbCf9kG6ylHNaxwu+FpssvnOXsY0M1YlAMrHankKFd5P4ppxqBpJnNIHTr678/NuXgjeA1H0EBmchc7jRScHoCaXxOkAJedtMNkulD8HDMGbc//9kqKBNWkEC6/8Egv4jyiD+K0QCRip7Bo4bhHmT49oO5sTlqkx+9yEYRZytxiE7H5+eIB76iG7RqE8cIaMYCzlheG1YOCQw3gcy00AXD8EfHo6iYmLvC1If3BPvkvbs9sIucMESSbsf8RjzzguN6LA8ESRCkgFutenOXuAOxGqwDgnTFTRDylU770q7gw5AER+a1vRppy+AO+mP8=
  api_key:
    secure: NHvQwwkB8FBFXIXHsDmk/34XAmQAxpe7zDvJMuvNN8S8G8dLOH5dN6Cv01eZ6m2KpTwDh76uSrVo1eJv9ljAV0Fj99O3JzwQ6U+N74eZPKwm4MIf2kmnyYC4sJtgbQTurnrZFrixC8lFuEPeZbBM8xD17lg+h1BgOxusaA+QtX3XLT14GZMKrezp9OtuGxyftIlNbc8knt+zvdF9npyb4E6uyRM5cnkyLrxz/JawehtynKv1eD60MvC4jQ3JLDPlaAM7Kx09zpLrgkbZd3jneYG0EHEuEEvFnOwyQfJJDnp9G9dxSv6rzjY+givzlT3XiGmuVTj6N9AT7lFobUySQGMxq5xiH8h4GfQhxPqMfFsqZaIWRuH5VLH+fPsjgmBHnrfyuipkGAkcxrKpu72yKxyQq0rATjyVoHgrfVf4hHxTvogjReK3/nAnpVKEgFxi6i9RTblkVddmuwhfauLT5pmbCU/YL0Wc2vu0RIU3NQTm9AoJvX/dSBfQFixVBWom5aphyYeZMxpGnjnZGVYYNcCMVBN5alqqnmTt9w/tTsYdiX4N11MN0cUScOvIZarY2JdvEwIE+h+r988/MuUCXF4IrRBzRKdp1ncA1nqalwKS8sJMMr4q2jCf9I33zMu/J42M2MIwYKmITijLyq0ue02n37w1egG438yRImC/f4Y=
  on:
    branch: master
cache:
  directories:
  - node_modules
before_install:
- BAZEL_VERSION=0.11.0
- BAZEL_DEB="bazel_${BAZEL_VERSION}-linux-x86_64.deb"
- wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/${BAZEL_DEB}
  -O "${BAZEL_DEB}"
- sudo dpkg -i ${BAZEL_DEB}
- rm ${BAZEL_DEB}
install:
- npm install
script:
- "./travis-ci-build.sh"
